name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./firmware/font"
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./firmware/scripts"
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./i18n"
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./tests"
          
  lint-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint
      - name: Lint
        run: |
          pylint firmware/font/*.py
          pylint firmware/scripts/*.py
          pylint i18n/*.py
          pylint src

  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Validate translations
        run: cd i18n && python3 i18n.py validate

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
      - name: Install project and its dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cache-clear tests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
      - name: Install project and its dependencies
        run: poetry install
      - name: Build coverage file
        run: poetry run pytest --cache-clear --cov src/krux --cov-report xml tests
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
